// Copies ABIs from Foundry artifacts into shared/src/abis.ts as `as const` arrays (typed by viem).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const contracts = [
  "MarketOracle",
  "CollateralRegistry",
  "LiquidityPool",
  "RiskManager",
  "FacilityFactory",
  "CreditFacility",
  "DemoFeed",
  "DemoVenue",
  "MockERC20",
];

let out = "// Generated by shared/scripts/export-abis.mjs. Do not edit; run `pnpm abis`.\n\n";
for (const name of contracts) {
  const artifact = JSON.parse(readFileSync(join(root, "contracts", "out", `${name}.sol`, `${name}.json`), "utf8"));
  out += `export const ${name[0].toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
}
writeFileSync(join(root, "shared", "src", "abis.ts"), out);
console.log(`Wrote ${contracts.length} ABIs to shared/src/abis.ts`);
